name: Spec Doc Release Workflow
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-spec-workflow:
    uses: colin-combe/mzTab/.github/workflows/ci.yml@master
  test-examples-workflow:
    uses: colin-combe/mzTab/.github/workflows/validate.yml@master
